#!/bin/bash
cp implementation/system.bit ../bit_files/roach2_tut_tge_2019_Mar_14_1313.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/roach2_tut_tge_2019_Mar_14_1313.bof
cp design_info.tab ../bit_files/roach2_tut_tge_2019_Mar_14_1313.info
gzip -c ../bit_files/roach2_tut_tge_2019_Mar_14_1313.bof  > ../bit_files/roach2_tut_tge_2019_Mar_14_1313.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/roach/seba/vector_voltmeter/models/tge/casper_model/roach2_tut_tge/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/roach2_tut_tge_2019_Mar_14_1313.fpg
