#################################################################
# Makefile generated by Xilinx Platform Studio 
# Project:/home/roach/seba/vector_voltmeter/models/tge/casper_model/roach2_tut_tge/XPS_ROACH2_base/system.xmp
#
# WARNING : This file will be re-generated every time a command
# to run a make target is invoked. So, any changes made to this  
# file manually, will be lost when make is invoked next. 
#################################################################

XILINX_EDK_DIR = /opt/Xilinx/14.7/ISE_DS/EDK

SYSTEM = system

MHSFILE = system.mhs

FPGA_ARCH = virtex6

DEVICE = xc6vsx475tff1759-1

INTSTYLE = default

XPS_HDL_LANG = vhdl
GLOBAL_SEARCHPATHOPT = 
PROJECT_SEARCHPATHOPT = 

SEARCHPATHOPT = $(PROJECT_SEARCHPATHOPT) $(GLOBAL_SEARCHPATHOPT)

SUBMODULE_OPT = 

PLATGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(SUBMODULE_OPT) -msg __xps/ise/xmsgprops.lst

OBSERVE_PAR_OPTIONS = -error yes

MICROBLAZE_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop.elf
MICROBLAZE_BOOTLOOP_LE = $(XILINX_EDK_DIR)/sw/lib/microblaze/mb_bootloop_le.elf
PPC405_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc405/ppc_bootloop.elf
PPC440_BOOTLOOP = $(XILINX_EDK_DIR)/sw/lib/ppc440/ppc440_bootloop.elf
BOOTLOOP_DIR = bootloops

BRAMINIT_ELF_IMP_FILES =
BRAMINIT_ELF_IMP_FILE_ARGS =

BRAMINIT_ELF_SIM_FILES =
BRAMINIT_ELF_SIM_FILE_ARGS =

SIM_CMD = xterm -e ./isim_system

BEHAVIORAL_SIM_SCRIPT = simulation/behavioral/$(SYSTEM)_setup.tcl

STRUCTURAL_SIM_SCRIPT = simulation/structural/$(SYSTEM)_setup.tcl

TIMING_SIM_SCRIPT = simulation/timing/$(SYSTEM)_setup.tcl

DEFAULT_SIM_SCRIPT = $(BEHAVIORAL_SIM_SCRIPT)

SIMGEN_OPTIONS = -p $(DEVICE) -lang $(XPS_HDL_LANG) -intstyle $(INTSTYLE) $(SEARCHPATHOPT) $(BRAMINIT_ELF_SIM_FILE_ARGS) -msg __xps/ise/xmsgprops.lst -s isim


CORE_STATE_DEVELOPMENT_FILES = pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
pcores/xaui_phy_v1_00_a/netlist/xaui_v9_1.ngc \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/kat_ten_gb_eth_v1_00_a/netlist/arp_cache.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/cpu_buffer.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_bram.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/rx_packet_fifo_dist.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_cpu_size_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_ctrl_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_packet_fifo.ngc \
pcores/kat_ten_gb_eth_v1_00_a/netlist/tx_fifo_ext.ngc \
pcores/xaui_phy_v1_00_a/netlist/xaui_v9_1.ngc \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/bram_block_custom_v1_00_a/netlist/dummy.edn \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/xaui_infrastructure.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/xaui_infrastructure_low.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/xaui_rx_steer.v \
pcores/xaui_infrastructure_v1_00_a/hdl/verilog/gtx_quad.v \
pcores/roach_infrastructure_v1_00_a/hdl/verilog/roach_infrastructure.v \
pcores/reset_block_v1_00_a/hdl/verilog/reset_block.v \
pcores/epb32_opb_bridge_v1_00_a/hdl/verilog/epb32_opb_bridge.v \
pcores/epb_infrastructure_v1_00_a/hdl/verilog/epb_infrastructure.v \
pcores/sys_block_v1_00_a/hdl/verilog/sys_block.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/gpio_controller.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/temac.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/sgmii_gtx.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/sgmii_phy.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/emac_mdio_wb.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/emac_mdio.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/emac_wrapper.v \
pcores/sfp_mdio_controller_v1_00_a/hdl/verilog/sfp_mdio_controller.v \
pcores/opb_register_ppc2simulink_v1_00_a/hdl/verilog/opb_register_ppc2simulink.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/arp_cache.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/cpu_buffer.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/kat_ten_gb_eth.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/opb_attach.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_bram.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/rx_packet_fifo_dist.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/vhdl/ten_gig_eth_mac_UCB.vhd \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_rx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tge_tx.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_ctrl_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_packet_fifo.v \
pcores/kat_ten_gb_eth_v1_00_a/hdl/verilog/tx_fifo_ext.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_phy.v \
pcores/xaui_phy_v1_00_a/hdl/verilog/xaui_v9_1.v \
pcores/opb_register_simulink2ppc_v1_00_a/hdl/verilog/opb_register_simulink2ppc.v \
pcores/bram_block_custom_v1_00_a/hdl/verilog/bram_block_custom.v \
pcores/bram_block_custom_v1_00_a/hdl/verilog/bram.v \
pcores/gpio_simulink2ext_v1_00_a/hdl/vhdl/gpio_simulink2ext.vhd

WRAPPER_NGC_FILES = implementation/system_xaui_infrastructure_inst_wrapper.ngc \
implementation/system_infrastructure_inst_wrapper.ngc \
implementation/system_reset_block_inst_wrapper.ngc \
implementation/system_opb0_wrapper.ngc \
implementation/system_epb_opb_bridge_inst_wrapper.ngc \
implementation/system_epb_infrastructure_inst_wrapper.ngc \
implementation/system_sys_block_inst_wrapper.ngc \
implementation/system_sfp_mdio_controller_inst_wrapper.ngc \
implementation/system_roach2_tut_tge_dest_ip_wrapper.ngc \
implementation/system_roach2_tut_tge_dest_port_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_wrapper.ngc \
implementation/system_xaui_phy_4_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxbadctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxeofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxs_ss_bram_ramblk_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxs_ss_bram_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxs_ss_ctrl_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxs_ss_status_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_rxvldctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txfullctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txs_ss_bram_ramblk_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txs_ss_bram_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txs_ss_ctrl_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txs_ss_status_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_txvldctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_linkup_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe0_tx_cnt_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_wrapper.ngc \
implementation/system_xaui_phy_5_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxbadctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxeofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxs_ss_bram_ramblk_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxs_ss_bram_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxs_ss_ctrl_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxs_ss_status_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rxvldctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txfullctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txofctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txs_ss_bram_ramblk_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txs_ss_bram_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txs_ss_ctrl_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txs_ss_status_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_txvldctr_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_linkup_wrapper.ngc \
implementation/system_roach2_tut_tge_gbe1_rx_frame_cnt_wrapper.ngc \
implementation/system_roach2_tut_tge_led0_gbe0_pulse_tx_wrapper.ngc \
implementation/system_roach2_tut_tge_led1_gbe0_up_wrapper.ngc \
implementation/system_roach2_tut_tge_led2_gbe1_pulse_rx_wrapper.ngc \
implementation/system_roach2_tut_tge_led3_gbe1_up_wrapper.ngc \
implementation/system_roach2_tut_tge_pkt_sim_enable_wrapper.ngc \
implementation/system_roach2_tut_tge_pkt_sim_payload_len_wrapper.ngc \
implementation/system_roach2_tut_tge_pkt_sim_period_wrapper.ngc \
implementation/system_roach2_tut_tge_rst_wrapper.ngc \
implementation/system_roach2_tut_tge_tx_snapshot_ss_bram_ramblk_wrapper.ngc \
implementation/system_roach2_tut_tge_tx_snapshot_ss_bram_wrapper.ngc \
implementation/system_roach2_tut_tge_tx_snapshot_ss_ctrl_wrapper.ngc \
implementation/system_roach2_tut_tge_tx_snapshot_ss_status_wrapper.ngc \
implementation/system_opb1_wrapper.ngc \
implementation/system_opb2opb_bridge_opb1_wrapper.ngc \
implementation/system_opb2_wrapper.ngc \
implementation/system_opb2opb_bridge_opb2_wrapper.ngc

POSTSYN_NETLIST = implementation/$(SYSTEM).ngc

SYSTEM_BIT = implementation/$(SYSTEM).bit

DOWNLOAD_BIT = implementation/download.bit

SYSTEM_ACE = implementation/$(SYSTEM).ace

UCF_FILE = data/system.ucf

BMM_FILE = implementation/$(SYSTEM).bmm

BITGEN_UT_FILE = etc/bitgen.ut

XFLOW_OPT_FILE = etc/fast_runtime.opt
XFLOW_DEPENDENCY = __xps/xpsxflow.opt $(XFLOW_OPT_FILE)

XPLORER_DEPENDENCY = __xps/xplorer.opt
XPLORER_OPTIONS = -p $(DEVICE) -uc $(SYSTEM).ucf -bm $(SYSTEM).bmm -max_runs 7

FPGA_IMP_DEPENDENCY = $(BMM_FILE) $(POSTSYN_NETLIST) $(UCF_FILE) $(XFLOW_DEPENDENCY)

SDK_EXPORT_DIR = SDK/SDK_Export/hw
SYSTEM_HW_HANDOFF = $(SDK_EXPORT_DIR)/$(SYSTEM).xml
SYSTEM_HW_HANDOFF_BIT = $(SDK_EXPORT_DIR)/$(SYSTEM).bit
SYSTEM_HW_HANDOFF_DEP = $(SYSTEM_HW_HANDOFF) $(SYSTEM_HW_HANDOFF_BIT)
