#!/bin/bash
cp implementation/system.bit ../bit_files/testing_2019_May_13_1626.bit
./mkbof_64 -o implementation/system.bof -s core_info.tab -t 3 implementation/system.bin
cp implementation/system.bof ../bit_files/testing_2019_May_13_1626.bof
cp design_info.tab ../bit_files/testing_2019_May_13_1626.info
gzip -c ../bit_files/testing_2019_May_13_1626.bof  > ../bit_files/testing_2019_May_13_1626.bof.gz
gzip -c implementation/system.bin > implementation/system.bin.gz
cat implementation/system.bin.gz >> /home/seba/Documents/Untitled_Folder/scripts/vector_voltmeter/models/dec2/part2_dec4/testing/XPS_ROACH2_base/extended_info.kcpfpg
cp extended_info.kcpfpg ../bit_files/testing_2019_May_13_1626.fpg
